### ISSUE TITLE
QUESTION: Is there still no easier method? 

### ISSUE THREAD

**Issue by dsfrederic** [YannickRe/azuredevops-buildagents#31]
Anno 2023 it seems like this method is quite complex. 

Is there no easier method to create **and share** these images across multiple orgs? 

In my situation I need to setup VMSS for different azure environments. Building these images per client is quite cumbersome. How would you tackle this situation?

**Comment by YannickRe** [comment]
Well, it depends on what you define as complex and what you expect from this.
What this project is about:

- Getting a VM image in your Azure Resource Group that is configured the same way Microsoft Hosted Agent images are configured
- It takes the extra step to set that image in one VMSS so future VM's in that scale set would use the new image, and the VMSS is managed by the DevOps org for scaling.

I don't totally get your requirement but essentially, after the image is generated, you can create your own process:

- Put it in a private Image gallery, like someone did within #18, and have your multiple VMSS configured to use the latest image from that Gallery. OR
- Have multiple VMSS configured (since you cannot reuse a VMSS across multiple DevOp orgs), and adjust the PowerShell script to update not one but all your VMSS's with the latest image. OR
- something totally different matching your requirement

I shared what worked for me, so none of you have to go through the hassle of figuring out how to build your own VHD from Microsoft's repo, but it for sure is sized to my requirements and not fully scalable for everyone's needs.
