### ISSUE TITLE
Issue creating windows2022 image

### ISSUE THREAD

**Issue by SH-JackCooper** [YannickRe/azuredevops-buildagents#32]
I'm currently having issues building a new win2022 image, ubuntu images are being built fine.

The pipeline runs for ~6hours fine then errors out with the below (tested on 3 seperate runs)
![image](https://user-images.githubusercontent.com/110113568/213466579-299736c9-4277-4eef-980b-b8b37a1550bb.png)

Any ideas? Or a way I could dig into the issue further?

Thanks,

**Comment by YannickRe** [comment]
This project always checks out the latest version of the code from Microsoft, and tries to build it, but that might also be broken code on their end. When I started this, they did not have Releases but now they do. Ideally, this project would checkout the code from the latest Release of an image version because that's what they deemed stable and would build.

This step needs to be adjusted for it, so it checks out the tagged release instead of the bleeding edge of their repository:
https://github.com/YannickRe/azuredevops-buildagents/blob/7dcee5913853c2c964eccc6eb32756858dfeca73/buildagent-generation-template.yml#LL50-L52C47

Either you adjust it yourself, or you wait until their code is stable or until I find the time to make this improvement.
I'm sorry I can't be of more help currently.

**Comment by erik-de-bont** [comment]
@SH-JackCooper There were some issue with the Windows 2022 last week. I was able to generate a Windows 2022 on the 19th, so it should be fixed now. You can see if there are any open issues [https://github.com/actions/runner-images/issues](https://github.com/actions/runner-images/issues)

@YannickRe  I can have a look to add an option in  the pipeline to select a stable or a beta image.

**Comment by erik-de-bont** [comment]
@SH-JackCooper  I ran into the same issue today. It seems related to the image from the pool your are using that builds the new image. I think I have a solution for this but I haven't tested it yet.

**Comment by erik-de-bont** [comment]
@SH-JackCooper  @YannickRe  The above solution didn't solve the issue, although I still recommend configuring a dedicated Agent Pool to build the runner Images.

As far as I understand issue seems related related Microsoft Defender for Endpoint already onboarded the build VM, when the runner VM is being build. This causes sysprep to fail. See [https://github.com/actions/runner-images/discussions/6251](https://github.com/actions/runner-images/discussions/6251) .

A workaround has been mentioned. I have implemented this workaround in the  buildgeneration-template.yml to this message, and am currently testing it. (takes 7 hours). When it works I will make a pull request. If you want to test yourself add the following task under 'Clone the Github Repository Task' in buildgeneration-template.yml

```
  - task: PowerShell@2
    displayName: 'Workaround for issue: https://github.com/actions/runner-images/discussions/6251'
    inputs:
      targetType: 'inline'
      script: |        
        $TemplateFile = "./runner-images/images/win/${{ parameters.image_type }}.json"
        Write-Host 'Attempting to modify $TemplateFile with workaround'
        ((Get-Content -path $TemplateFile -Raw) -replace '"type": "azure-arm",','"type": "azure-arm","azure_tags": { "ExcludeMdeAutoProvisioning": "True" },') | Set-Content -Path $TemplateFile               
        Write-Host "$TemplateFile modified"
        Get-Content -path $TemplateFile -Raw
```

**Comment by erik-de-bont** [comment]
I have tested the solution, and it solved the problem.

**Comment by erik-de-bont** [comment]
@SH-JackCooper  @YannickRe  A workaround has been implemented in my fork [https://github.com/erik-de-bont/azuredevops-buildagents](https://github.com/erik-de-bont/azuredevops-buildagents) and a pull request has been made  for implementation in this repository,

**Comment by SH-JackCooper** [comment]
@erik-de-bont Perfect, thanks for this! I've just tested this working also - was tearing my hair out thinking it was something enviroment specific.

**Comment by erik-de-bont** [comment]
@SH-JackCooper  @YannickRe  Unfortunately [my pull request](https://github.com/actions/runner-images/pull/7043) to implement this solution in the runner images repository has been rejected. Since my previous pull request was also rejected, it is getting more difficult to use the action/runner-images  without modifications in corporate environment. Therefore I have to keep the workaround steps in buildpipeline.

**Comment by SamBonavika** [comment]
I used the code from Erik's clone and was able to build a Win2022 image.

I did run into a strange error when using the "East US" location, but once I changed to "East US 2" everything worked.
