### ISSUE TITLE
Build VM stops 

### ISSUE THREAD

**Issue by bkarakashev** [YannickRe/azuredevops-buildagents#4]
Hi,

I am not sure why my build is stoping I can not see any failed tests or any errors but getting this:
![image](https://user-images.githubusercontent.com/6206509/114663806-c79e6f80-9cf2-11eb-8d4b-9dbfa51bbcfa.png)

Any idea what is going wrong?

Thanks

**Comment by YannickRe** [comment]
No idea, but mine stopped too... I noticed they had issues with their builds, and since we're just using their templates => ours will fail too. You can follow their builds at https://github.visualstudio.com/virtual-environments/_build?definitionId=71&_a=summary

I only trigger a build of my images when I see that theirs has had a successful run, so the chances are higher that mine succeed too. I restarted mine this morning, about an hour ago: building the ubuntu image on a Windows Server build agent. I'll let you know the results.

**Comment by YannickRe** [comment]
I have just successfully build an Ubuntu2004 image using a Windows Server 2019 build agent (with Packer 1.6.6). I'll run a build again to build Ubuntu using the new Ubuntu build agent I just created (which should have Packer 1.7.2).

**Comment by bkarakashev** [comment]
Still not working for me, it is stopping always on the same spot and now error logs not really sure why is breaking.
I am in contact with Microsoft at the moment lets see if they will be able to help.

**Comment by bkarakashev** [comment]
my script is failing here when running this helper script:
https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/git.sh

**Comment by bkarakashev** [comment]
@YannickRe are you using a Windows VM or Linux VM for the packer build

**Comment by YannickRe** [comment]
I'm sorry for that, but I have no idea. I have today run two builds of Ubunto 20.04, one on a Windows Server 2019 with Packer 1.6.6 and another one on Ubuntu 20.04 with packer 1.7.2. Both ran successfully.

**Comment by bkarakashev** [comment]
so the issue was with our Subscription set up,
