### ISSUE TITLE
packer is not available for hosted agent

### ISSUE THREAD

**Issue by System-Admins-ath** [YannickRe/azuredevops-buildagents#43]
When using the pipeline the packer tool is not available.
Adding the extension "packer" and adding the task packertool into the buildagent-generation-template is required:
```
    - task: PackerTool@0
      inputs:
        version: 
```

**Comment by YannickRe** [comment]
Can you show me what error you are getting? This surprises me since all Microsoft Hosted Agents have Packer in their list of pre-installed software:

- https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md 
- https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
- https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
- https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md

**Comment by System-Admins-ath** [comment]
Both Packer and AZ CLI is not regonized:
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/94194707/d7f7bdcc-032f-47d3-9630-24e7108b057b)

![image](https://github.com/YannickRe/azuredevops-buildagents/assets/94194707/3c40a41f-f1fe-4d15-ac58-e49f469027a2)

**Comment by YannickRe** [comment]
I just tried it, and it runs without a problem for me.
Can you show me the output when you select the "Image Generation" top level node in your run?
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/9973962/32c216fe-9ceb-4ab2-8f8a-4e059665790f)

**Comment by YannickRe** [comment]
@System-Admins-ath Any update? Did it work out for you in the end?

**Comment by System-Admins-ath** [comment]
@YannickRe : yeah, worked. I think it had something to do, with the agent running the pipeline.

A feature idea is to allow modification of sizes for the os disks

**Comment by YannickRe** [comment]
Good that it worked out eventually.
Regarding the OS Disk size > that's unfortunately something you'll have to pick up with the original image creators https://github.com/actions/runner-images This repo just provides a reproducible way of creating them in a pipeline.
