### ISSUE TITLE
Question: - Build Agent application

### ISSUE THREAD

**Issue by Marcus-James-Adams** [YannickRe/azuredevops-buildagents#5]
Hi, I hope you don't mind me asking a question as I'm seeming to get conflicting information on this.

Background
I'm using terraform to create my virtual machine scale set so trying to work out what custom extensions my VM's in the scale set should call.

Do you need to install the azure devops build agent and configure it for your projects etc or does that happen automatically as part of the Azure Devops Provisioning process? 

I see some early examples show that you have to create a custom script to install the agent and others just seem to ignore this step.

Does the MS image include the agent s nothing needs installing?

Cheers
##Confused##

**Comment by YannickRe** [comment]
No worries, it is a valid question. The image does NOT contain the build agent.

- If you create your Scale Set, and you let Azure manage the provisioning/scaling of this Set then you'll need some sort of custom script/extension. This extension should run when a new VM is added so that it installs the build agent and registers itself with your DevOps environment and it gets used for builds.
- If you do what I did in my blog post: you don't need the custom script. A Scale Set registered as a Scale Set Agent Pool is managed by DevOps entirely. So when DevOps decides to scale and add a new VM, it'll make sure that the build agent is installed and the new VM is registered.

Hope that clears it?

**Comment by Marcus-James-Adams** [comment]
Ahh, perfect that's the clarification bit - yes I'm setting them up registered as a sale set agent pool - so nothing to worry about.  thanks for your help.
