### ISSUE TITLE
Always use "main" branch instead of releases, based on feedback

### ISSUE THREAD

**Issue by System-Admins-ath** [YannickRe/azuredevops-buildagents#68]
Currently it's not possible to build the Windows images due to an error in the downloaded releases.
Based on feedback from the /actions/runner team, this should always use the main branch.

https://github.com/actions/runner-images/issues/8732

![image](https://github.com/YannickRe/azuredevops-buildagents/assets/94194707/9b1aeb7b-5e9b-4706-b4f3-d122c23c7017)

**Comment by YannickRe** [comment]
H @System-Admins-ath ,

This has been the guideline forever with that repository, because of the way they do things. While running the packer build, all the binaries for all the software are downloaded on the fly. Sometimes these are fixed versions, sometimes they are just the latest version available at that point. This means that none of the releases or prereleases (or any subsequent run of the same snapshot of code from that repo) will necessarily result in the same image.

It's a challenge for my project because a run might work now and fail in 3h and work again in 6h, and I'm usually taking the heat for it although it's rarely caused by my "wrapper" 😄.
We used to only run on the latest and greatest code from the runner-images repo, but some people wanted to option to go the latest release or pre-release. That's why we introduced those selections when starting your build: alpha (which is latest and greatest), pre-release (latest pre-release tag for a specific image type), or release (latest release tag for a specific image type).

I hope this clarifies things?

**Comment by System-Admins-ath** [comment]
So i could just use alpha, and that will use the main branch? :-)

On 6 Nov 2023, at 15.29, Yannick Reekmans ***@***.***> wrote:

﻿
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

H @System-Admins-ath<https://github.com/System-Admins-ath> ,

This has been the guideline forever with that repository, because of the way they do things. While running the packer build, all the binaries for all the software are downloaded on the fly. Sometimes these are fixed versions, sometimes they are just the latest version available at that point. This means that none of the releases or prereleases (or any subsequent run of the same snapshot of code from that repo) will necessarily result in the same image.

It's a challenge for my project because a run might work now and fail in 3h and work again in 6h, and I'm usually taking the heat for it although it's rarely caused by my "wrapper" 😄.
We used to only run on the latest and greatest code from the runner-images repo, but some people wanted to option to go the latest release or pre-release. That's why we introduced those selections when starting your build: alpha (which is latest and greatest), pre-release (latest pre-release tag for a specific image type), or release (latest release tag for a specific image type).

I hope this clarifies things?

**Comment by YannickRe** [comment]
Exactly!

**Comment by System-Admins-ath** [comment]
Perfect! Then the issue can be closed!

On 6 Nov 2023, at 15.32, Yannick Reekmans ***@***.***> wrote:

﻿
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Exactly!
