### ISSUE TITLE
Hosted pipeline agent

### ISSUE THREAD

**Issue by McAdamz** [YannickRe/azuredevops-buildagents#8]
Hello, the documentation mentioned the initial run could be run on the Hosted Pipeline, and then switched to the custom image, but this isn't the case, as the Hosted Pipelines have a 6 hour maximum run time.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

![image](https://user-images.githubusercontent.com/87050311/125524238-2ea73b2c-76ed-42ef-83d1-45a27af2ab8d.png)

**Comment by YannickRe** [comment]
I never noticed that limitation, and I ran my first image on a paid Microsoft hosted agent with success.
Have you tried it and did it fail?

**Comment by sagoo33** [comment]
Hi @YannickRe, yes, I tried it twice using the MS Hosted Agent, both times failed at 6 hours 15minutes.

![image](https://user-images.githubusercontent.com/3021022/125700929-8b34e16b-e584-4f31-9cad-3c8339eb9011.png)

I got the scripts to work by creating a self hosted agent with a temporary VM, and then manually installing chocolaty, packer and the latest Powershell. 
It took a number of failed attempts before I found the required packages needed to run the scripts fully.

Thank you for your time in putting this together, but I thought it would be useful to update your readme to mention the Hosted Agent has timeout of 6hours and would not be able to create a windows image using it.

**Comment by YannickRe** [comment]
Thank you for informing me! Feel free to submit the PR, but otherwise I'll keep this open until I get to adjusting the readme myself.

Probably this would work too: Hosted Agent to build a Linux Agent, and then use the Linux Agent to build your Windows Agent. Not sure what would be quicker: this extra step with the Linux agent or you trying to create a minimal image to create the full image 😀

Glad you made it work, and again: thank you!

**Comment by CurlyBytes** [comment]
yes this is a bummer, im trying to create a vmss with Linux first then will run the CICD scripts using the vmss agent to create windows image

**Comment by CurlyBytes** [comment]
![image](https://user-images.githubusercontent.com/55616292/128536397-7e8ffafc-6dd0-4c23-acaf-e8eb5cd3201d.png)

yes this is a bummer, im trying to create a vmss with Linux first then will run the CICD scripts using the vmss agent to create windows image

**Comment by spoelstraethan** [comment]
Microsoft is looking to change their scripts to only install the LATEST of each .NET runtime, which should drop the end to end runtime a huge amount, this change is going to take place September 6 I believe.

The crazy thing is running the same scripts on our own hosted agent only took 5 hours, but depending on when you try to run it in the public pipelines you might run into "noisy neighbors" where all the other people using public pipelines slow down the build due to I/O or network contention.

**Comment by Marcus-James-Adams** [comment]
Have you got the URL that explains what MS are going to change in
September.  That would be really helpful.

**Comment by YannickRe** [comment]
@CurlyBytes thank you for the PR, I merged it and made some other README updates too
@spoelstraethan thank you for the heads up, that would help a lot for sure
@Marcus-James-Adams they mention the change here: https://github.com/actions/virtual-environments/issues/3809

Given that the README is updated regarding the original issue, I will now close this issue.
